name: Generate snake animation

on:
  # Execute every 12 hours
  schedule: 
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
      

    steps:
      # Checkout the repository to access files like `languages.yml`
      - name: Checkout repository
        uses: actions/checkout@v3

      # Extrac most used language from the GitHub API
      - name: Get the most used language
        run: |
          repos=$(curl -s "https://api.github.com/users/JulianHL/repos" | jq -r '.[].name')

          top_language=""
          max_lines=0

          # Declare an array to store language lines
          declare -A language_lines  

          # Iterate each of my repositories
          for repo in $repos; do
            languages=$(curl -s "https://api.github.com/repos/JulianHL/$repo/languages")

            # Iterate each language of the repository
            for language in $(echo "$languages" | jq -r 'keys[]'); do

              #add lines to each language
              lines=$(echo "$languages" | jq -r ".\"$language\"")
              
              if [ -z "${language_lines[$language]}" ]; then
                language_lines[$language]=$lines  # Si el lenguaje no existe, lo inicializamos
              else
                language_lines[$language]=$((language_lines[$language] + lines))  # Si ya existe, sumamos las líneas
              fi
              
              if (( ${language_lines[$language]} > max_lines )); then
                top_language=$language
                max_lines=${language_lines[$language]}
              fi
            done
          done
          sed -i '/^most_used_language=/d' $GITHUB_ENV
          echo "most_used_language=$top_language" >> $GITHUB_ENV


      # Extract the color of the most used language from languages.yml
      - name: Get language color
        id: color
        run: |
          # Download languages.yml from the GitHub Linguist repository
          curl -o languages.yml https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml
          
          # Extract the color associated with the most used language
          COLOR=$(sed -n '/${{ env.most_used_language }}:/,/color:/p' languages.yml| grep "color:" | awk '{print $2}')
          COLOR=${COLOR//\"/} # Remove quotes if present
          sed -i '/^language_color=/d' $GITHUB_ENV
          echo "language_color=$COLOR" >> $GITHUB_ENV

      # Generate the snake.svg using the extracted color
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Modify snake color in SVG
        run: |
         sed -i 's/--cs:purple/--cs:${{ env.language_color }}/g' dist/snake.svg

      # Push the updated snake.svg to the output branch
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
